specVersion: 1.0.0
name: comdex-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: Comdex project by TonyMoon
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: comdex-1
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  endpoint: "https://rpc-comdex.zenchainlabs.io/"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://comdex-rpc.polkachu.com/"
  chainTypes:
    cosmos.slashing.v1beta1:
      file: ./proto/cosmos/slashing/v1beta1/tx.proto
      messages:
        - MsgUnjail
    cosmos.gov.v1beta1:
      file: ./proto/cosmos/gov/v1beta1/tx.proto
      messages:
        - MsgVoteWeighted
    cosmos.gov.v1beta1.gov:
      file: ./proto/cosmos/gov/v1beta1/gov.proto
      messages:
        - WeightedVoteOption
    publicawesome.stargaze.claim.v1beta1:
      file: ./proto/stargaze/claim/v1beta1/tx.proto
      messages:
        - MsgInitialClaim
dataSources:
  - kind: cosmos/Runtime
    startBlock: 6000000
    mapping:
      file: ./dist/index.js
      handlers:
        # Using block handlers slows your project down as they can be executed with each and every block. Only use if you need to
        # - handler: handleBlock
        #   kind: cosmos/BlockHandler
        # Using transaction handlers without filters slows your project down as they can be executed with each and every block
        # - handler: handleTransaction
        #   kind: cosmos/TransactionHandler
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: execute
            messageFilter:
              type: /cosmwasm.wasm.v1.MsgExecuteContract
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: /cosmos.tx.v1beta1.Tx
